config/routes.rb
Rails.application.routes.draw do



  resources :selfie_verifications
  resources :address_verifications
  resources :nationalid_verifications
  resources :user_infos
  resources :user_verifications
  resources :user_verfications
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :watchdogs
      resources :users
      resources :countries
      resources :affilate_programs
      post "users/create" => "users#create"
      get "homepage" => "users#homepage"
      post "confirmmail" => "users#confirmmail"
      post "resend_confirmmail" => "users#resend_confirmmail"
      get "two_factor" => "users#get_two_factor"
      post "two_factor" => "users#post_two_factor"
      get "statistics" => "users#statistics"
      get "lock_unlock_account" => "users#lock_unlock_account"
      get "send_confirmation_email" => "users#send_confirmation_email"
      get "change_confirmation_code" => "users#change_confirmation_code"
      get "confirm_google_code" => "users#confirm_google_code"
      get "set_otp_code" => "users#set_otp_code"
      get "user_log" => "watchdogs#user_log"
      get "active_sessions" => "logins#active_sessions"
      post 'auth_user' => 'authentication#authenticate_user'
      post "unlockaccount" => "authentication#unlockaccount"
      post "send_invitation_email" => "affilate_programs#send_invitation_email"
      post 'getEditToken' => 'authentication#getEditToken'
    end
  end



  resources :affilate_programs
  resources :countries
  resources :logins
  resources :verifications
  resources :watchdogs
  resources :users
  root "users#homepage"
  get "confirmmail" => "users#confirmmail"
  get "unlockaccount" => "users#unlockaccount"
  get "two_factor" => "users#get_two_factor"
  post "two_factor" => "users#post_two_factor"
  get "user_log" => "watchdogs#user_log"
  get "statistics" => "users#statistics"
  get "lock_unlock_account" => "users#lock_unlock_account"
  get "active_sessions" => "logins#active_sessions"
  get "send_confirmation_email" => "users#send_confirmation_email"
  get "change_confirmation_code" => "users#change_confirmation_code"
  get "confirm_google_code" => "users#confirm_google_code"
  get "set_otp_code" => "users#set_otp_code"
  get "affilate-program/:refered_by" => "affilate_programs#send_invitation"
  post "send_invitation_email" => "affilate_programs#send_invitation_email"
  #get "edit_password/:id" => "users#edit_password" , :as => "edit_password" 
  get "add_admin" => "users#add_admin"
  post "add_admin" => "users#add_admin_post"
  get "error_page" => "logins#error_page"
  get "lock_page" => "logins#lock_page"
  post "lock_page" => "logins#check_to_unlock"
  



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
    before_action :authenticate_request!, except: [:create, :confirmmail, :resend_confirmmail]
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token
    attr_reader :current_user
    
   
    #before_action :get_google_auth ,only: [:show, :edit, :update,:index]
    #require 'rqrcode'

    # GET /users
    # GET /users.json
    # =begin
    # @api {get} /api/v1/users List all users
    # @apiVersion 0.3.0
    # @apiName GetUsers
    # @apiGroup User
    # @apiDescription get details of all users.
    # @apiExample Example usage:
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMn0.HjzZehfkPaDES35pXYwdlXNydDMWhwayCjMBs5KUcOE" -i http://localhost:3000/api/v1/users
    #
    # @apiSuccess {Integer}    id                   User's-ID.
    # @apiSuccess {Integer}    uuid                 User's-uuid.
    # @apiSuccess {String}     account_number       User's account_number.
    # @apiSuccess {String}     telephone            User's telephone.
    # @apiSuccess {Integer}    roleid               User's role id.
    # @apiSuccess {String}     username             User's username.
    # @apiSuccess {String}     firstname            User's first name.
    # @apiSuccess {String}     lastname             User's last name.
    # @apiSuccess {Integer}    disabled             User's account status.
    # @apiSuccess {Integer}    status               Email confirmation status.
    # @apiSuccess {Integer}    loginattempts        User's login attempts.
    # @apiSuccess {Integer}    failedattempts       User's failed attempts.
    # @apiSuccess {Integer}    account_currency     User's account currency.
    # @apiSuccess {Integer}    country_id           User's country id.
    # @apiSuccess {String}     email                User's email.
    # @apiSuccess {Integer}    country_id           User's country.
    # @apiSuccess {Datetime}   created_at           date of creating the User.
    # @apiSuccess {Datetime}   updated_at           date of updating the User.
    #
    # @apiSuccessExample Success-Response:
    # HTTP/1.1 200 OK
    #   {
    # "id": 1,
    #  "uuid": "8dddd2c5",
    #  "roleid": 1,
    #  "username": "amira",
    #  "firstname": "amira",
    #  "lastname": "amira2",
    #  "disabled": 1,
    #  "loginattempts": 7,
    #  "status": 1,
    #  "created_at": "2018-07-30T13:19:38.031Z",
    #  "updated_at": "2018-08-02T13:02:55.156Z",
    #  "email": "amira.elfayhhome@servicehigh.com",
    #  "failedattempts": 0,
    #  "account_number": "PS100000001",
    #  "telephone": "00201007460059",
    #  "account_currency": 0,
    #  "country_id": 1
    # },
    # {
    # "id": 2,
    #  "uuid": "dd89adb1",
    #  "roleid": 1,
    #  "username": "amira2",
    #  "firstname": "amira2",
    #  "lastname": "amira2",
    #  "disabled": 1,
    #  "loginattempts": 0,
    #  "status": 0,
    #  "created_at": "2018-07-30T13:19:58.031Z",
    #  "updated_at": "2018-08-02T13:02:55.156Z",
    #  "email": "amira.elfayhhome@servicehigh.com",
    #  "failedattempts": 0,
    #  "account_number": "PS100000002",
    #  "telephone": "0020102982852",
    #  "account_currency": 0,
    #  "country_id": 1
    # }
    # @apiError NoAccessRight Only authenticated users can access the data.
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 401 Unauthorized
    #     {
    #       "error": "NoAccessRight"
    #    }
    # =end

  def index
    flash[:error]= "Not Allowed"
    respond_to do |format|
        if current_user.roleid == 1
          @users = User.all             
          format.json { render json: @users }                
        else            
          format.json { render json: flash }
        end
    end
  end

    # GET /users/1
    # GET /users/1.json
    # =begin
    # @api {get} /api/users/{:id} Get User Data
    # @apiVersion 0.3.0
    # @apiName GetUser
    # @apiGroup User
    # @apiDescription get details of specific user.
    # @apiExample Example usage:
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -i http://localhost:3000/api/v1/users/1
    #
    # @apiSuccess {Integer}    id                   Users-ID.
    # @apiSuccess {String}     username             Users username.
    # @apiSuccess {String}     firstname            Users firstname.
    # @apiSuccess {String}     lastname             Users lastname.
    # @apiSuccess {String}     email                Users email.
    # @apiSuccess {Integer}    country_id           Users country.
    # @apiSuccess {Datetime}   created_at           date of creating the User.
    # @apiSuccess {Datetime}   updated_at           date of updating the User.
    #
    # @apiError NoAccessRight Only authenticated users can access the data.
    # @apiError UserNotFound   The <code>id</code> of the User was not found.
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 401 Unauthorized
    #     {
    #       "error": "NoAccessRight"
    #    }
    # @apiErrorExample Error-Response:
    #     HTTP/1.1 404 Not Found
    #     {
    #       "error": "UserNotFound"
    #    }
    # =end

  def show    
    @user = User.where("id =? " ,params[:id]).first
      respond_to do |format|
        if current_user.roleid == 1 or current_user.id == params[:id].to_i        
          format.json { render json: @user }
          # @qr = RQRCode::QRCode.new(@user.provisioning_uri("payers"), :size => 7, :level => :h )
        else
          format.json { render json: "Not Allowed" }
        end
      end
  end
 
    # GET /statistics 
    # =begin
    # @api {get} /api/v1/statistics?&account_status={:search_status} Get Users Statistics
    # @apiVersion 0.3.0
    # @apiName GetUsersstatistics
    # @apiGroup User
    # @apiDescription get statistics of all users.
    # @apiExample Example usage:
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -i 'http://localhost:3000/api/v1/statistics?&account_status=confirmed'
    #
    # @apiSuccess {Integer}    id                   Users-ID.
    # @apiSuccess {String}     username             Users username.
    # @apiSuccess {String}     firstname            Users firstname.
    # @apiSuccess {String}     lastname             Users lastname.
    # @apiSuccess {String}     email                Users email.
    # @apiSuccess {Integer}    country_id           Users country.
    # @apiSuccess {Datetime}   created_at           date of creating the User.
    # @apiSuccess {Datetime}   updated_at           date of updating the User.
    #
    # @apiError NoAccessRight Only authenticated users can access the data.
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 401 Unauthorized
    #     {
    #       "error": "NoAccessRight"
    #    }
    # =end

  def statistics
      @result = User.statics(params[:account_status].to_s)
      respond_to do |format|
        if current_user.roleid == 1
          format.json { render json: @result }
        else
          format.json { render json: "Not Allowed" }
        end
      end
  end

    #disable/enable account
    # GET /lock_unlock_account 
    # =begin
    # @api {get} /api/v1/lock_unlock_account?id={:user-id} change account status
    # @apiVersion 0.3.0
    # @apiName GetAccountStatus
    # @apiGroup User
    # @apiDescription change account status for user.
    # @apiExample Example usage:
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -i http://localhost:3000/api/v1/lock_unlock_account?id=1
    #
    # @apiSuccessExample Success-Response:
    # HTTP/1.1 200 OK
    # {
    # "mseeage": "user has been enabled/disabled"
    # }
    #
    # @apiError NoAccessRight Only authenticated users can perform this action.
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 401 Unauthorized
    #     {
    #       "error": "NoAccessRight"
    #    }
    # =end 

  def lock_unlock_account
      @user = User.where("id = ?",params[:id].to_i).first
    if @user.disabled == 1
        @user.disabled = 0
        @status = "enabled"
    else
        @user.disabled = 1
        @status = "disabled"
    end   
    respond_to do |format|
      if current_user.roleid == 1
        @user.save
        format.json { render json: @user.username + " has been " + @status }
      else
        format.json { render json: "Not Allowed" }
      end
    end 
  end

  def homepage   
    # curl -H "Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMX0.ikUiajq9UFTi4OJDDGR2Xqk79U5vtiRWJaa8HgneqC4" -H "Content-Type: application/json" -X GET http://localhost:3000/api/v1/homepage
    render json: {'logged_in' => true} 
  end

    # confirm user mail after registeration
    # POST /confirm user mail after registeration
    # =begin
    # @api {post} /api/v1/confirmmail confirm user mail
    # @apiVersion 0.3.0
    # @apiName POSTconfirmmail
    # @apiGroup User
    # @apiDescription confirm user mail after registeration.
    # @apiExample Example usage:
    # curl -X POST  http://localhost:3000/api/v1/confirmmail -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"email": "engamira333@gmail.com","token": "3aa4e716"}' 
    #
    # @apiSuccessExample Success-Response:
    # HTTP/1.1 200 OK
    # {
    #   "result : true"
    # }
    #
    # @apiError required_parameter_missing wrong code .
    # @apiError required_parameter_missing2 wrong email .
    #
    # @apiErrorExample Response (example):
    #     HTTP/1.1 400 Badrequest
    #     {
    #       "result : false"
    #       "error": "MissingData"
    #       "status": 400- Bad Request
    #    }
    # =end 

  def confirmmail
      @email = params[:email]
      @token = params[:token]
      @user = User.where("email =?",@email ).first
        if @user

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
    if respond_to?(:before_action)
      before_action :redirect_signed_in_users, only: [:create, :new]
      skip_before_action :require_login, only: [:create, :new], raise: false
      skip_before_action :authorize, only: [:create, :new], raise: false
    else
      before_filter :redirect_signed_in_users, only: [:create, :new]
      skip_before_filter :require_login, only: [:create, :new], raise: false
      skip_before_filter :authorize, only: [:create, :new], raise: false
    end
    skip_before_action :check2fa ,only: [:new, :destroy, :create]
    skip_before_action :check_active_session ,only: [:new, :destroy, :create]

  
    def new
      @user = user_from_params
      render template: "users/new"
    end
  
    def create
      @user = user_from_params
  
      if @user.save
        sign_in @user
        redirect_back_or url_after_create
      else
        render template: "users/new"
      end
    end
  
    private
  
    def avoid_sign_in
      warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
        "deprecated. Use `redirect_signed_in_users` instead. " +
        "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
        " or `skip_before_action :avoid_sign_in` as well"
      redirect_signed_in_users
    end
  
    def redirect_signed_in_users
      if signed_in?
        redirect_to Clearance.configuration.redirect_url
      end
    end
  
    def url_after_create
      Clearance.configuration.redirect_url
    end
  
    def user_from_params
      email = user_params.delete(:email)
      password = user_params.delete(:password)
  
      Clearance.configuration.user_model.new(user_params).tap do |user|
        user.email = email
        user.password = password
      end
    end
  
    def user_params
      params[Clearance.configuration.user_parameter] || Hash.new
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_admin.html.erb
<div class="padding">
    <div class="box">
        <div class="box-header">
             <h2>Add New Admin</h2>
        </div>
        <div class="box-divider m-0"></div>
            <div class="box-body">
                <%= form_for @user , :url => add_admin_path do |form| %>
                    <% if @user.errors.any? %>
                         <div id="error_explanation">
                             <%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved: 
                             <ul>
                                <% @user.errors.full_messages.each do |message| %>
                                   <li><%= message %></li>
                                <% end %>
                             </ul>
                         </div>
                    <% end %>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">User Name</label>
                                <div class="col-sm-10">
                                    <%= form.text_field :username , class: 'form-control' , :required => true %>
                                </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Email</label>
                                <div class="col-sm-10">
                                    <%= form.text_field :email, type: 'email' , class: 'form-control', :required => true %>
                                </div>
                      </div>
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Password</label>
                               <div class="col-sm-10">
                                    <%= form.password_field :password , class: 'form-control' , :required => true %>
                               </div>
                      </div>
                      
                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Country</label>
                             <div class="col-sm-10">
                                 <%= form.select :country_id, options_for_select( Country.all.collect {|p| [ p.Full_Name, p.id ] } ), {}, {:class => 'form-control c-select'} %>
                             </div>
                      </div>

                      <div class="form-group row">
                          <label class="col-sm-2 form-control-label">Account Status</label>
                               <label class="ui-switch ui-switch-lg m-t-xs m-r">
                                    <%= form.check_box :disabled,{:checked => !@user.disabled},0,1 %>    
                                    <i></i>
                               </label>
                      </div>

                       <div class="form-group row m-t-md">
                           <div class="col-sm-offset-2 col-sm-10">
                               <button type="submit" class="btn btn-fw primary" id="submit" >Submit</button>
                           </div>
                       </div>
                <% end %>
            </div>
    </div>
</div>
    

app/views/users/create.html.erb
<%= debug params%>

app/views/users/edit_password.html.erb
<h1>Editing User Password </h1>
    <%= form_for @user do |form| %>
        <% if @user.errors.any? %>
           <div id="error_explanation">
               <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
               <ul>
                   <% @user.errors.full_messages.each do |message| %>
                       <li><%= message %></li>
                   <% end %>
               </ul>
           </div>
       <% end %>

       <div class="password-field">
            <%= form.label :password %>
            <%= form.password_field :password %>
       </div><br>

       <div class="password-field">
            <%= form.label :confirm_password %>
            <%= form.password_field :confirm_password %>
       </div><br>

       <div class="submit-field">
             <%= form.submit  %>
       </div>
    <% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/get_two_factor.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Payers - Payment Facilator</title>
  <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <!-- for ios 7 style, multi-resolution icon of 152x152 -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
  <link rel="apple-touch-icon" href="/assets/images/logo.png">
  <meta name="apple-mobile-web-app-title" content="Flatkit">
  <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
  <meta name="mobile-web-app-capable" content="yes">
  <link rel="shortcut icon" sizes="196x196" href="/assets/images/logo.png">
  
  <!-- style -->
  <link rel="stylesheet" href="/assets/animate.css/animate.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/glyphicons/glyphicons.css" type="text/css" />
  <link rel="stylesheet" href="/assets/font-awesome/css/font-awesome.min.css" type="text/css" />
  <link rel="stylesheet" href="/assets/material-design-icons/material-design-icons.css" type="text/css" />

  <link rel="stylesheet" href="/assets/bootstrap/dist/css/bootstrap.min.css" type="text/css" />
  <!-- build:css ../assets/styles/app.min.css -->
  <link rel="stylesheet" href="/assets/styles/app.css" type="text/css" />
  <!-- endbuild -->
  <link rel="stylesheet" href="/assets/styles/font.css" type="text/css" />
</head>
<body>
  <div class="app" id="app">
  <% flash.each do |key, value| -%>
    <div class="col-sm-3">
            <div class="box-color accent pos-rlt">
              <span class="arrow bottom b-accent"></span>
              <div class="box-body">
                 <div id="flash_<%= key %>"><%=h value %></div>
              </div>
            </div>
    </div>
  <% end %>
<!-- ############ LAYOUT START-->
  <div class="center-block w-xxl w-auto-xs p-y-md">
    <div class="navbar">
      <div class="pull-center">
        <div ui-include="'/views/blocks/navbar.brand.html'"></div>
      </div>
    </div>
    <div class="p-a-md box-color r box-shadow-z1 text-color m-a">
	  <div class="m-b text-sm">
		<% if current_user.active_otp == 1%>
			Email Code Authentication
		<% else %>
			Google Authentication
		<% end %>
        
      </div>
      <%= form_for :confirm , :url => two_factor_path do |f| %>
		<div class="md-form-group float-label">
		  <%= f.text_field :code , class: 'md-input', :required => true %>
          <label>Authentication Code</label>
        </div>
              
        <button type="submit" class="btn primary btn-block p-x-md">Send</button>
	  <% end %>
    </div>
    <% if current_user.active_otp == 2 %>
        <div class="p-v-lg text-center">
            <div class="m-b"><a ui-sref="access.forgot-password" href="/send_confirmation_email" class="text-primary _600">has a problem with google authentication?, confirm by Email</a></div>		
		</div>
	<% end %>   
    
  </div>

<!-- ############ LAYOUT END-->

  </div>
<!-- build:js scripts/app.html.js -->
<!-- jQuery -->
  <script src="/libs/jquery/jquery/dist/jquery.js"></script>
<!-- Bootstrap -->
  <script src="/libs/jquery/tether/dist/js/tether.min.js"></script>
  <script src="/libs/jquery/bootstrap/dist/js/bootstrap.js"></script>
<!-- core -->
  <script src="/libs/jquery/underscore/underscore-min.js"></script>
  <script src="/libs/jquery/jQuery-Storage-API/jquery.storageapi.min.js"></script>
  <script src="/libs/jquery/PACE/pace.min.js"></script>

  <script src="scripts/config.lazyload.js"></script>

  <script src="/scripts/palette.js"></script>
  <script src="/scripts/ui-load.js"></script>
  <script src="/scripts/ui-jp.js"></script>
  <script src="/scripts/ui-include.js"></script>
  <script src="/scripts/ui-device.js"></script>
  <script src="/scripts/ui-form.js"></script>
  <script src="/scripts/ui-nav.js"></script>
  <script src="/scripts/ui-screenfull.js"></script>
  <script src="/scripts/ui-scroll-to.js"></script>
  <script src="/scripts/ui-toggle-class.js"></script>

  <script src="/scripts/app.js"></script>

  <!-- ajax -->
  <script src="/libs/jquery/jquery-pjax/jquery.pjax.js"></script>
  <script src="/scripts/ajax.js"></script>
<!-- endbuild -->
</body>
</html>

app/views/users/post_two_factor.html.erb
<%= debug @user_code%>
<%= debug @sent_code %>

app/views/users/show.html.erb
<div class="padding">
  
      <div class="box">
        <div class="box-header">
          <span class="label danger pull-right"><%= @user.id %></span>
          <h3>User Profile</h3>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th>Username</th>
              <td><%= @user.username %></td>
            </tr>
          </thead>
          <tbody>
          <% if @user.avatar.attached? %>
            <tr>
              <th>Profile Picture</th>
              <td> <%= image_tag @user.avatar.variant(resize: "100x100")  %></td>
            </tr>
          <% end %>
            <tr>
              <th>firstname</th>
              <td> <%= @user.firstname %></td>
            </tr>
            <tr>
              <th>lastname</th>
              <td> <%= @user.lastname %></td>
            </tr>
            <tr>
              <th>Email</th>
              <td> <%= @user.email %></td>
            </tr>
            <tr>
              <th>account_number</th>
              <td> <%= @user.account_number %></td>
            </tr>
            <tr>
              <th>uuid</th>
              <td> <%= @user.uuid %></td>
            </tr>
            <tr>
              <th>telephone</th>
              <td> <%= @user.telephone %></td>
            </tr>
            <tr>
              <th>roleid</th>
              <td> <%= @user.roleid %></td>
            </tr>
            <tr>
              <th>country</th>
              <td> <%= @user.country.Full_Name %></td>
            </tr>
            <tr>
              <th>Account Currency</th>
                <% if !(@user.account_currency)%>
                   <td> <%= "USD" %></td>
                <% else %>
                   <td> <%= @user.country.Currency %></td>
                <% end%>
            </tr> 
          <% if @user.secret_code != nil and @user.secret_code != "" %>                
            <tr>
              <th>Secret Code</th>
              <td><%= "********" + @user.secret_code[@user.secret_code.length - 3 ,3] %></td>
            </tr> 
          <% end %>                
            <tr>
              <th>Active Otp</th>
              <% if @user.active_otp == 1 %>
                  <td> <%= "Email Code" %></td>
              <% elsif @user.active_otp == 2 %>
                  <td> <%= "Google Authentication Code" %></td>
              <% end %>              
            </tr>
            <tr>
              <th>Invitation Code</th>
              <td> <%= @user.invitation_code %></td>
            </tr>
            <tr>
              <th>Invitation Link</th>
              <td><%= "https://clearance.herokuapp.com/affilate-program/" + @user.invitation_code %></td>
            </tr>
            <tr>
              <th>Send Invitation Mail</th>
              
              <td> <%= form_for :invitiation, url: send_invitation_email_path do |form| %> 
                <div class="row">
               <div class="col-lg-4">
                      <div class="text-field">
                         <%= form.label :email %>
                         <%= form.text_field :email %>
                      </div>
                      </div>
                      <div class="col-lg-1">          
                      <button type="submit" style="padding:5px;height:30px;width:50px;background-color:#6887ff !important; border-color:#6887ff" class="btn btn-primary waves-effect waves-light m-t-15 text-center"><%= 'send' %> </button>
                      </div></div> <% end %></td>
            </tr>
            <% if @user.nationalid_verification != nil %>
              <tr>
                 <th>National ID Verification</th>
                 <td> <%= link_to 'show National Id Verification'.html_safe, { :controller => :nationalid_verifications,:action=>:show,:id => @user.nationalid_verification.id} %></td>
              </tr>
            <% end %>
            <% if @user.address_verification != nil %>
              <tr>
                 <th>Address Verification</th>
                 <td><%= link_to 'show Address Verification'.html_safe, { :controller => :address_verifications,:action=>:show,:id => @user.address_verification.id} %></td>
              </tr>
            <% end %>
            <% if @user.selfie_verification != nil %>
              <tr>
                 <th>Selfie Verification</th>
                 <td> <%= link_to 'show Selfie Verification'.html_safe, { :controller => :selfie_verifications,:action=>:show,:id => @user.selfie_verification.id} %></td>
              </tr>
            <% end %>
            <% if current_user.roleid == 1 %>
            <tr>
              <th>Change Account Status</th>
              <% if @user.disabled == 0 %>
                 <td><%= link_to 'Disable User'.html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => @user.id} %></td>
              <% else %>
                 <td><%= link_to 'Enable User'.html_safe, { :controller => :users,:action=>:lock_unlock_account,:id => @user.id} %></td>
              <% end %>
            </tr>
            <% end %>
            <tr>
              <th>Other Links</th>
              <td> <%= link_to 'Edit Profile', edit_user_path(@user) %> - <%= link_to 'show user log'.html_safe, { :controller => :watchdogs,:action=>:user_log,:id => @user.id} %> - <%= link_to t('show active sessions').html_safe, { :controller => :logins,:action=>:active_sessions,:id => @user.id} %> - </td>
            </tr>
            
                    
           
          </tbody>
        </table>
      </div>
</div>

app/views/users/update.html.erb
<%= debug params %>
<%= debug params[:user][:confirm_password] %>
<%= debug params[:confirm_password] %>